global:
  scrape_interval:     15s
  evaluation_interval: 30s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    ec2_sd_configs:
      - port: 9100
        region: 'us-east-1'
        profile: '<Name of AWS profile>'
    relabel_configs:
      - source_labels: [__meta_ec2_tag_aws_autoscaling_groupName]
        action: keep
        regex: '<Enter filter>'
        
relabel_configs:
      - source_labels: [__meta_ec2_tag_aws_autoscaling_groupName]
        action: keep
        regex: '<Enter filter>'
